### ISSUE TITLE
ERC20 contract deployment fails on zkevm-chain L2

### ISSUE THREAD

**Issue by ntampakas** [privacy-scaling-explorations/zkevm-chain#5]
We are trying to deploy a simple ERC20 contract against zkevm-chain testnet.
Initially, we tried to deploy it connecting to the L2 leader node.
This failed with the following error:
`  ERROR[06-21|12:22:20.463] RPC method eth_estimateGas crashed: impossible case: address was not present in access list during sstore opgoroutine 538 [running]:`
(more details here: https://hackmd.io/@ntampakas/Sy--oVkqq)

Then, we followed the same exact process to L1 and it worked fine.

**Comment by ed255** [comment]
The error shown is coming from geth https://github.com/ethereum/go-ethereum/blob/67454df08b512ea33aa4c246ee405cf4b418ec35/core/vm/operations_acl.go#L49
This is a panic, so it's a situation that shouldn't not occur in geth under normal circumstances.

A hypothesis on why this is happening is that we may have a "weird" configuration of geth due to the EIPs we have enabled/disabled that create a particular configuration, which never existed historically, that has not been tested in geth.  For example, it could be that geth believes that we are in a fork where an access list must be added to a tx; but we disabled the EIP that introduces the access list; or something similar.

I think this requires some analysis of:
1. How the client is generating txs
2. How the L2 geth is configured (with the disabled/enabled EIPs)
3. How geth reaches to the panic, and how that path relates to point 1 and 2.

@pinkiebell do you have any thoughts or ideas about why this is happening?  If nothing comes to mind I can do a more thorough investigation by analyzing the 3 points I listed.

**Comment by pinkiebell** [comment]
Probably due to 2930, https://github.com/privacy-scaling-explorations/zkevm-chain/tree/master/docs#layer-2---go-ethereum

This issue sounds similar for something I encountered in the past. I will take a look, this probably happened during a git-merge

**Comment by pinkiebell** [comment]
added a regression test in [commit](https://github.com/privacy-scaling-explorations/zkevm-chain/commit/25b3489dcea99e10f350bbc119eeef0bc53ce772)

I'm waiting for the go-ethereum docker workflow and will push another commit that uses the new go-ethereum image.
This should fix and track the sstore gas calculation issue, however, we may also decide on another solution to handle this.
That's why I keep this issue open for now 😄

**Comment by AronisAt79** [comment]
Thanks @ed255 and @pinkiebell for taking care of this. Maybe push the change into a temporary branch until we decide what the final solution will be?

**Comment by pinkiebell** [comment]
Ah, pushed already ^^ . let's keep this open until we settle.

**Comment by AronisAt79** [comment]
> 

My bad :). Missed the issue closure by a few seconds!

**Comment by ed255** [comment]
> The problem re-emerged with enabling `3529` again. I think it makes sense to disable the panic in our fork because we live without 2930 but new gas calculation EIPs like 3529.
> 
> What do you think @ed255 ?

I've taken a deeper look at the geth code and I think we may encounter a deeper issue.

Disabling the panic sounds fine as a workaround.  But I'm currently thinking that this panic shouldn't be reached:
- We have disabled the optional access lists that go into the transaction
- But we have enabled the warm/cold state/storage costs model, which uses access lists.

So what we want is: the transaction doesn't include an optional access list; but geth calculates an access list for state/storage accesses.  In the SSTORE case, geth should create add the account to the access list when the call begins, and on SSTORE add the slot to the access list.  But this panic is happening because on SSTORE, the account is not in the access list, which means that it wasn't added when the call began (it seems this function is not being called? https://github.com/ethereum/go-ethereum/blob/f49e29833084d65cae0d2eba71e5788e6d9996c0/core/state/statedb.go#L1000)
If geth is not using access lists, then the gas cost we verify in the circuits won't match the gas cost of the tx executed by geth.

**Comment by pinkiebell** [comment]
`PrepareAccessList` is called in our case, it depends on `rules.IsBerlin`which evaluates to true.
But I agree that we should add some tests. Do you think some prebuilt `eth_estimateGas` fixtures for common cases will do it?

**Comment by ed255** [comment]
> But I agree that we should add some tests. Do you think some prebuilt `eth_estimateGas` fixtures for common cases will do it?

This sounds good!  In the `zkevm-circuits` repo we have a utility to generate bytecode from opcodes https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/2aa9875d9bcf5dd8937af7d88f121dad1a8877ed/eth-types/src/bytecode.rs#L178
Example usage: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/2aa9875d9bcf5dd8937af7d88f121dad1a8877ed/bus-mapping/src/evm/opcodes/sstore.rs#L133

I wanted to share this because it could be useful for these tests.

> Hah, found code rot: https://github.com/privacy-scaling-explorations/go-ethereum/blob/cf9429370a226744a7be1c39d0d92805915767f4/core/vm/evm.go#L422

Ah!  That was it :P  I see that you already reverted commenting the panic, and removed that check.  Hopefully with this change now the panic will not appear.  @AronisAt79 @ntampakas once the docker image of the geth node with the last commit is ready, could you try running the entire test flow again, and see if the panic is no longer there?

**Comment by ntampakas** [comment]
Everything works fine now and the contract was successfully deployed on L2.
Thank you a lot @ed255 and @pinkiebell for your efforts! (:

**Comment by pinkiebell** [comment]
I added a more complex `access list` test and verified it by disabling london or berlin EIPs on the l1 node and test against the l2 node. [This](https://github.com/privacy-scaling-explorations/zkevm-chain/blob/master/coordinator/tests/chain.rs#L638) test should pass with the assumption that there are no gas+refund differences on our l1/l2 setup even if optional access list are not supported on l2.

**Comment by pinkiebell** [comment]
@ed255 What's is the most straightforward way to run the bus-mapping/integration tests with our geth fork?

**Comment by ed255** [comment]
> @ed255 What's is the most straightforward way to run the bus-mapping/integration tests with our geth fork?

We currently have two kinds of tests that depend on go-ethereum

## Integration tests

Located [here](https://github.com/privacy-scaling-explorations/zkevm-circuits/tree/main/integration-tests) and managed with the script `run.sh`.  They test 4 different blocks with ETH transfers and ERC20 transfers in various situations.  This is tested for circuit-input-builder alone (bus-mapping), and also in convination with the EVM / state circuit with the mock prover.

Changing the geth used here can be done by changing the image used in the [docker-compose.yml](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/integration-tests/docker-compose.yml)

## Unit tests

We have plenty of unit tests inside the package `bus-mapping` and `zkevm-circuits` that depend on go-ethereum as a library via [this utility] to execute blocks and get traces from the execution.  To use a forked go-ethereum we would need to update [go.mod](https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/geth-utils/go.mod) to point to our fork and maybe edit some the code to replicate the configuration of enabled/disabled EIPs at https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/d567bb23fe16eedfb15ff8a67063de201724ae49/geth-utils/gethutil/trace.go#L126

**Comment by pinkiebell** [comment]
fyi, I've integrated the ethereum tests into our zkevm fork.
The diff against upstream was also reduced being now based on `berlin` and only adapt 2 EIPs from `london`. [view](https://github.com/privacy-scaling-explorations/zkevm-chain/tree/master/docs#layer-2---go-ethereum)

Thus, gas calculation will be like `london` but only supporting the legacy transaction type. The access list costs are then basically the same as with an empty access list.

zkevm branch for ethereum/tests
https://github.com/privacy-scaling-explorations/eth-tests/tree/zkevm
