### ISSUE TITLE
soundness problem: the keccak circuit selectors are all disabled?

### ISSUE THREAD

**Issue by lispc** [privacy-scaling-explorations/zkevm-chain#67]
https://github.com/privacy-scaling-explorations/zkevm-chain/blob/68982510b93fd34e06f5d2f444a3807b90668b40/prover/src/compute_proof.rs#L76

here the circuit used to gen vk has no keccak inputs, so all the fixed columns (like q_enable q_absorb) in keccak circuit are not enabled? 

I think keccak circuit also need a xx_pad_to.

**Comment by pinkiebell** [comment]
Thanks! This is possible related with https://github.com/privacy-scaling-explorations/zkevm-circuits/issues/790

**Comment by lispc** [comment]
@ed255 @han any thoughts on this?

**Comment by ed255** [comment]
@lispc If I understand you correctly, what you mean is that currently the keccak circuit is different each time depending on the `keccak_inputs`, and we should add a parameter like `max_rounds` so that we can build a static keccak circuit that works for blocks that require `0` to `max_rounds` of keccak right?

I believe there's a simple solution to have a fixed length keccak circuit by adding padding rounds that compute the keccak of the empty array, so that we can always have the same values in the fixed columns regardless of the `keccak_inputs`. I'm assuming that the keccak circuit has a repeating pattern for each round, and that evaluating the keccak of the empty array only consumes one round in the circuit.  But maybe there are better solutions?  I'm not very familiar with the keccak circuit @ChihChengLiang what do you think is the best way to add support for a `max_rounds` parameter in the keccak circuit?

**Comment by lispc** [comment]
Yes that is what i am worried

**Comment by Brechtpd** [comment]
The way I saw this being done (and previously talked with Carlos about) is indeed to just hash no data inputs repeatedly to get to the fixed number of hashes supported by the circuit. I don\t believe there's a downside to this simple method, and this way we don't require any special state in the circuit just for doing this kind of padding, so keeps things simple.

**Comment by ed255** [comment]
> The way I saw this being done (and previously talked with Carlos about) is indeed to just hash no data inputs repeatedly to get to the fixed number of hashes supported by the circuit. I don\t believe there's a downside to this simple method, and this way we don't require any special state in the circuit just for doing this kind of padding, so keeps things simple.

@Brechtpd Do you think we could add an argument `max_rounds: usize` in `KeccakPackedCircuit::assign_from_witness` such that when it's `== 0`, it's ignored, and then it's `> 0` the inputs are extended with empty arrays to reach `max_rounds` and obtain a fixed size circuit?  This way it's very easy for the consumer of the keccak circuit build a fixed circuit regardless of the inputs.

**Comment by Brechtpd** [comment]
Yes I think that should be very easy, will create a PR for that.

**Comment by ed255** [comment]
Resolved via https://github.com/privacy-scaling-explorations/zkevm-circuits/pull/858
